#!/usr/bin/env bash
# Find the PID of the process named "4-to_infinity_and_beyond"

PID=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$PID" ]; then
    # If the process exists, kill it
    kill "$PID"
fi
