#!/usr/bin/env bash
# Let dig a little bit about the subject

log_file="apache-access.log"
if [ ! -f "$log_file" ]; then
    echo "Error: Apache log file '$log_file' not found."
    exit 1
fi

# Use awk to group visitors by IP and HTTP status code, count occurrences, and sort by occurrence number
awk '{print $1, $9}' "$log_file" | sort | uniq -c | sort -rn
